export const types = {
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  OPEN_LOADER: 'OPEN_LOADER',
  CLOSE_LOADER: 'CLOSE_LOADER',
  SET_ERROR: 'SET_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
  CLEAR_MESSAGE: 'CLEAR_MESSAGE',
  RESET_PWD_SUCCESS: 'RESET_PWD_SUCCESS',
  UPDATE_PWD_SUCCESS: 'UPDATE_PWD_SUCCESS',
  VERIFY_ACCOUNT_SUCCESS: 'VERIFY_ACCOUNT_SUCCESS',
};
